global:
  scrape_interval: 5s   # her 5 saniyede bir metric toplar

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "user_service"
    static_configs:
      - targets: [ "user_service:8000" ]

  - job_name: "account_service"
    static_configs:
      - targets: [ "account_service:8001" ]

  - job_name: "transaction_service"
    static_configs:
      - targets: [ "transaction_service:8004" ]
